apiVersion: v1
kind: ResourceQuota
metadata:
  name: cms-quota
  namespace: cms 
spec:
  hard:
    pods: "10"
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 5Gi
